title: "BitDevs Cotonou"
tagline: "BitDevs Cotonou is the community for those interested in discussing and participating in the research and development of Bitcoin and related protocols in Cotonou."

menu:
  - { name: "About", url: "/about" }
  - { name: "Events", url: "/events" }
  - { name: "Blog", url: "/blog" }
  - { name: "X", url: "https://x.com/BitdevsCotonou", external: true }
  - {
      name: "Discussion",
      url: "https://chat.whatsapp.com/IfsmzGeleeUBwvy1AJ6W9U",
      external: true,
    }
