title: 'BitDevs Cotonou'
tagline: 'BitDevs Cotonou is the Cotonou community for those interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Events', url: '/events'}
  - {name: 'Blog', url: '/blog'}
  - {name: 'Luma', url: 'https://lu.ma/bitdevscotonou', external: true}
  - {name: 'Cities', url: '/cities'}
